version: '3'
services:
  api-call-touch:
    build: ./apps/call-touch/
    container_name: api-call-touch
    restart: always
    user: node
    ports:
      - 3000:3000
    depends_on: 
      - mongo-call-touch
    volumes:
      - ./.env:/opt/app/.env
  mongo-call-touch:
    image: mongo:4.4.4
    container_name: mongo-call-touch
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db